#!/usr/bin/env bash
# Regenerate apps/api/seed/seed.sql from the running Postgres container.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/apps/api/seed/seed.sql"
CONTAINER="${POSTGRES_CONTAINER:-bridge-postgres-1}"
PGUSER="${POSTGRES_USER:-bridge}"
PGDB="${POSTGRES_DB:-bridge}"

TABLES=(
  personas
  users
  user_journeys
  summaries
  matches
  connection_cards
)

dump_args=()
for t in "${TABLES[@]}"; do
  dump_args+=(-t "$t")
done

tmp="$(mktemp)"
docker exec "$CONTAINER" pg_dump -U "$PGUSER" -d "$PGDB" \
  --data-only --inserts --column-inserts --no-owner --no-privileges \
  "${dump_args[@]}" 2>/dev/null \
  | grep -v '^\\restrict' | grep -v '^\\unrestrict' > "$tmp"

cat > "$OUT" <<'HEADER'
-- Bridge database seed (auto-generated by scripts/dump-seed.sh)
--
-- Apply:
--   PGPASSWORD=bridge psql -h localhost -U bridge -d bridge -f apps/api/seed/seed.sql
--
-- Regenerate:
--   ./scripts/dump-seed.sh

BEGIN;

TRUNCATE TABLE
  connection_cards,
  wingman_sessions,
  summaries,
  matches,
  user_journeys,
  magic_link_tokens,
  deletion_audit,
  users,
  personas
RESTART IDENTITY CASCADE;

HEADER

# Re-order inserts: pg_dump order is not FK-safe
for t in "${TABLES[@]}"; do
  awk -v table="$t" '
    /^INSERT INTO public\.'"$t"'/ { print }
  ' "$tmp"
done >> "$OUT"

echo "" >> "$OUT"
echo "COMMIT;" >> "$OUT"
rm -f "$tmp"

echo "Wrote $OUT"
